### PR TITLE
Adding seaborn

### PR DESCRIPTION
**Pull request by sawula**
Adding seaborn library.  In part to confirm the procedure for adding libraries.

### CODE REVIEW

**Comment by sawula** [comment]
Adding seaborn.

**Comment by damianavila** [comment]
@sawula I guess you do not have enough permissions to self-merge this one yet, am I right?

**Comment by sawula** [comment]
@damianavila Yes.  I believe I do not have the permission merge this pull request myself.  @sgibson91 wondered whether I would earn that permission after my first merged pull request.  This was a test of that conjecture as well as a case to work through to document the process.

**Comment by sgibson91** [comment]
> @sgibson91 wondered whether I would earn that permission after my first merged pull request.

Ah sorry, I meant that someone has to approve the tests to run for the first PR (now they should run automatically). We should absolutely give @sawula enough permissions to self-merge so the engineering team aren't a bottle neck :)

**Comment by sawula** [comment]
i think this 5-day wait is for all of the times in my life that i've been impatient about something. i'm personally proud of my growth.

**Comment by sgibson91** [comment]
@sawula I've just sent you an invite to collaborate on the project. Once you accept, you should be able to merge this PR yourself :)

**Pull request merged**
